# mod_tex: distributed LaTeX-rendering over Apache
# Copyright (C) 2007 Peter Danenberg
# See doc/COPYING for details.
class Types(object):
    LATEX = 'latex'
    DVIPNG = 'dvipng'
    MATH = 'math'
    GRAPHVIZ = 'graphviz'
    GNUPLOT = 'plot'
    DOT = 'dot'
    FDP = 'fdp'
    CIRCO = 'circo'
    TWOPI = 'twopi'
    NEATO = 'neato'
    PNG = 'png'
    MIDI = 'midi'
    GHOSTSCRIPT = 'gs'
    LILYPOND = 'music'
    EPS = 'eps'
    CHESS = 'chess'
    METAPOST = 'metapost'
    FEYN = 'feyn'
    XYMTEX = 'xymtex'
    SGF2DG = 'go'
    TEX = 'tex'
    TENGWAR = 'teng'
    GREEK = 'greek'
