.ig
mod_tex: distributed LaTeX-rendering over Apache
Copyright (C) 2007 Peter Danenberg
See doc/COPYING for details.
..
.so heading.ms
.XH 1 Copyright
.LP
mod_tex: distributed LaTeX-rendering over Apache
.br
Copyright \(co 2007 Peter Danenberg
.PP
You should have received a copy of the GNU General Public License version 2
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
